#开发环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: website
    password: weile1314
    url: jdbc:mysql://120.79.2.77/website?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
    #文件上传大小配置
  http:
    multipart:
      max-file-size: 10MB
  freemarker:
    settings:
      number_format: 0.##
server:
  port: 8080
  address: localhost
upload:
  path: /Users/zhaoxiang/update
