#开发环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yhyc2018
    url: jdbc:mysql://localhost/website?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
    #文件上传大小配置
  http:
    multipart:
      max-file-size: 10MB
  freemarker:
    settings:
      number_format: 0.##

server:
  port: 80
  address: www.cdrysj.com
#  ssl:
#    key-store: classpath:static/cert/www.cdrysj.com.pfx
#    key-store-password: yhyc2018
#    key-store-type: PKCS12


upload:
  path: D:\upload
